# netlify.toml
[functions]
 	node_bundler = "esbuild"
  external_node_modules = ["@fastify/autoload"]
  included_files = [
    "dist/**"
  ]

[build]
    base = "fantamd-be"
    command = "npm run build"
    functions = "functions"
    publish = "dist"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/serverless/:splat"
  status = 200