# netlify.toml
[functions]
    node_bundler = "esbuild"
    included_files = ["dist/**/*.js"]

[build]
    base = "fantamd-be"
    command = "npm run build"
    functions = "functions"
    publish = "dist"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200