# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Tests and Coverage on Commit for fantamd-be

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fantamd-be-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./fantamd-be
        
    steps:
      - uses: actions/checkout@v5
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present
      
      - name: Run tests with coverage and containers
        run: npm run test:run

